Repository heroku/heroku-buildpack-python, pull requests merged in 2020-04, with the labels that each got.

#940 Barbeque/patch 1
  CHANGELOG.md
  README.md
Labels: documentation-issue, languages-health-squad-review

#945 More recent changelog update
  CHANGELOG.md
Labels: changelog-update, documentation-issue

#895 Geos deprecation
  CHANGELOG.md
  bin/steps/gdal
  bin/steps/geo-libs
  test/run-deps
Labels: experience-improvement, languages-health-squad-review, maintainability-issue, scheduled-for-release

#930 Fix old Django version detection
  CHANGELOG.md
  bin/steps/pip-install
  test/fixtures/not-old-django/requirements.txt
  test/fixtures/old-django/requirements.txt
  test/run-features
Labels: documentation-issue, experience-improvement, languages-health-squad-review, scheduled-for-release

#946 Release prep: changelog update
  CHANGELOG.md
Labels: changelog-update, languages-health-squad-review, scheduled-for-release

#948 Bugfix: Caching on subsequent redeploys
  CHANGELOG.md
  bin/compile
  bin/steps/python
  bin/steps/sqlite3
  hatchet.lock
  spec/hatchet/python_spec.rb
  test/run-deps
Labels: Bug, caching, languages-health-squad-review

#910 Fix runtime.txt generation when using pipenv
  CHANGELOG.md
  README.md
Labels: documentation-issue, in progress

#969 [changelog skip] Hatchet Regression Tests
  .travis.yml
  Gemfile
  Gemfile.lock
  hatchet.json
  hatchet.lock
  spec/hatchet/ci_spec.rb
  spec/hatchet/python_spec.rb
  spec/spec_helper.rb
Labels: languages-health-squad-review
