Repository heroku/heroku-buildpack-python, pull requests merged in 2020-08, with the labels that each got.

#1029 Replace 'master' branch references with 'main'
  .travis.yml
  CHANGELOG.md
  README.md
  etc/publish.sh
Labels: c: development

#1034 Add a configuration file for Git2Gus
  .git2gus/config.json
Labels: c: development

#1035 Travis: Move hatchet ci:setup to before_script
  .travis.yml
Labels: c: development

#1036 Tests: Update Hatchet dependencies
  .travis.yml
  Gemfile.lock
Labels: c: development

#1037 Add config file for Dependabot
  .github/dependabot.yml
Labels: c: development

#1046 Tests: Update Hatchet from 6.0.0 to 7.0.0
  Gemfile.lock
Labels: c: development

#1040 Fix the security update version check message for PyPy
  CHANGELOG.md
  bin/steps/python
  test/fixtures/pypy2_7/runtime.txt
  test/fixtures/pypy2_7_warn/requirements.txt
  test/fixtures/pypy2_7_warn/runtime.txt
  test/fixtures/pypy3_6/runtime.txt
  test/fixtures/pypy3_6_warn/requirements.txt
  test/fixtures/pypy3_6_warn/runtime.txt
  test/run-versions
Labels: c: user-experience, t: bug

#1041 Remove unused etc/ci-setup.sh
  etc/ci-setup.sh
Labels: c: development

#1042 Remove unused .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: c: development

#1043 Remove unused vendor/test-utils
  CHANGELOG.md
  vendor/test-utils
Labels: c: development

#1044 Rename confusing PYPY_* variables
  bin/default_pythons
  bin/steps/python
  test/run-versions
Labels: c: development

#1047 Travis: Remove Hatchet credentials from .travis.yml
  .travis.yml
Labels: c: development

#1045 Travis: Correctly skip Hatchet on PRs from forks
  .travis.yml
Labels: c: development

#1048 Update the Python 3.4.10 build script to use the correct Python version
  CHANGELOG.md
  builds/runtimes/python-3.4.10
  test/run-versions
Labels: t: bug

#1049 Switch the remaining build formulas to the shared script approach
  builds/runtimes/python-2.7.17
  builds/runtimes/python-2.7.18
  builds/runtimes/python-3.4.9
Labels: c: development

#1051 Travis: Switch to Ubuntu 20.04 base image
  .travis.yml
Labels: c: development

#1052 Make etc/publish.sh executable
  etc/publish.sh
Labels: c: development
